/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as OnboardingIndexImport } from './routes/onboarding/index'
import { Route as AppDashboardImport } from './routes/_app/dashboard'
import { Route as AppServicosIndexImport } from './routes/_app/servicos/index'
import { Route as AppRelatoriosIndexImport } from './routes/_app/relatorios/index'
import { Route as AppProntuariosIndexImport } from './routes/_app/prontuarios/index'
import { Route as AppProfissionaisIndexImport } from './routes/_app/profissionais/index'
import { Route as AppPacientesIndexImport } from './routes/_app/pacientes/index'
import { Route as AppFinanceiroIndexImport } from './routes/_app/financeiro/index'
import { Route as AppConfiguracoesIndexImport } from './routes/_app/configuracoes/index'
import { Route as AppCaixaIndexImport } from './routes/_app/caixa/index'
import { Route as AppAuditoriaIndexImport } from './routes/_app/auditoria/index'
import { Route as AppAssinaturaIndexImport } from './routes/_app/assinatura/index'
import { Route as AppAjudaIndexImport } from './routes/_app/ajuda/index'
import { Route as AppAgendaIndexImport } from './routes/_app/agenda/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingIndexRoute = OnboardingIndexImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

const AppServicosIndexRoute = AppServicosIndexImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => AppRoute,
} as any)

const AppRelatoriosIndexRoute = AppRelatoriosIndexImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => AppRoute,
} as any)

const AppProntuariosIndexRoute = AppProntuariosIndexImport.update({
  id: '/prontuarios/',
  path: '/prontuarios/',
  getParentRoute: () => AppRoute,
} as any)

const AppProfissionaisIndexRoute = AppProfissionaisIndexImport.update({
  id: '/profissionais/',
  path: '/profissionais/',
  getParentRoute: () => AppRoute,
} as any)

const AppPacientesIndexRoute = AppPacientesIndexImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => AppRoute,
} as any)

const AppFinanceiroIndexRoute = AppFinanceiroIndexImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => AppRoute,
} as any)

const AppConfiguracoesIndexRoute = AppConfiguracoesIndexImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => AppRoute,
} as any)

const AppCaixaIndexRoute = AppCaixaIndexImport.update({
  id: '/caixa/',
  path: '/caixa/',
  getParentRoute: () => AppRoute,
} as any)

const AppAuditoriaIndexRoute = AppAuditoriaIndexImport.update({
  id: '/auditoria/',
  path: '/auditoria/',
  getParentRoute: () => AppRoute,
} as any)

const AppAssinaturaIndexRoute = AppAssinaturaIndexImport.update({
  id: '/assinatura/',
  path: '/assinatura/',
  getParentRoute: () => AppRoute,
} as any)

const AppAjudaIndexRoute = AppAjudaIndexImport.update({
  id: '/ajuda/',
  path: '/ajuda/',
  getParentRoute: () => AppRoute,
} as any)

const AppAgendaIndexRoute = AppAgendaIndexImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/agenda/': {
      id: '/_app/agenda/'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/ajuda/': {
      id: '/_app/ajuda/'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AppAjudaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/assinatura/': {
      id: '/_app/assinatura/'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AppAssinaturaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/auditoria/': {
      id: '/_app/auditoria/'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AppAuditoriaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/caixa/': {
      id: '/_app/caixa/'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AppCaixaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/configuracoes/': {
      id: '/_app/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/financeiro/': {
      id: '/_app/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/pacientes/': {
      id: '/_app/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AppPacientesIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/profissionais/': {
      id: '/_app/profissionais/'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AppProfissionaisIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/prontuarios/': {
      id: '/_app/prontuarios/'
      path: '/prontuarios'
      fullPath: '/prontuarios'
      preLoaderRoute: typeof AppProntuariosIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/relatorios/': {
      id: '/_app/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/servicos/': {
      id: '/_app/servicos/'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AppServicosIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAgendaIndexRoute: typeof AppAgendaIndexRoute
  AppAjudaIndexRoute: typeof AppAjudaIndexRoute
  AppAssinaturaIndexRoute: typeof AppAssinaturaIndexRoute
  AppAuditoriaIndexRoute: typeof AppAuditoriaIndexRoute
  AppCaixaIndexRoute: typeof AppCaixaIndexRoute
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
  AppPacientesIndexRoute: typeof AppPacientesIndexRoute
  AppProfissionaisIndexRoute: typeof AppProfissionaisIndexRoute
  AppProntuariosIndexRoute: typeof AppProntuariosIndexRoute
  AppRelatoriosIndexRoute: typeof AppRelatoriosIndexRoute
  AppServicosIndexRoute: typeof AppServicosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAgendaIndexRoute: AppAgendaIndexRoute,
  AppAjudaIndexRoute: AppAjudaIndexRoute,
  AppAssinaturaIndexRoute: AppAssinaturaIndexRoute,
  AppAuditoriaIndexRoute: AppAuditoriaIndexRoute,
  AppCaixaIndexRoute: AppCaixaIndexRoute,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
  AppPacientesIndexRoute: AppPacientesIndexRoute,
  AppProfissionaisIndexRoute: AppProfissionaisIndexRoute,
  AppProntuariosIndexRoute: AppProntuariosIndexRoute,
  AppRelatoriosIndexRoute: AppRelatoriosIndexRoute,
  AppServicosIndexRoute: AppServicosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/agenda': typeof AppAgendaIndexRoute
  '/ajuda': typeof AppAjudaIndexRoute
  '/assinatura': typeof AppAssinaturaIndexRoute
  '/auditoria': typeof AppAuditoriaIndexRoute
  '/caixa': typeof AppCaixaIndexRoute
  '/configuracoes': typeof AppConfiguracoesIndexRoute
  '/financeiro': typeof AppFinanceiroIndexRoute
  '/pacientes': typeof AppPacientesIndexRoute
  '/profissionais': typeof AppProfissionaisIndexRoute
  '/prontuarios': typeof AppProntuariosIndexRoute
  '/relatorios': typeof AppRelatoriosIndexRoute
  '/servicos': typeof AppServicosIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/agenda': typeof AppAgendaIndexRoute
  '/ajuda': typeof AppAjudaIndexRoute
  '/assinatura': typeof AppAssinaturaIndexRoute
  '/auditoria': typeof AppAuditoriaIndexRoute
  '/caixa': typeof AppCaixaIndexRoute
  '/configuracoes': typeof AppConfiguracoesIndexRoute
  '/financeiro': typeof AppFinanceiroIndexRoute
  '/pacientes': typeof AppPacientesIndexRoute
  '/profissionais': typeof AppProfissionaisIndexRoute
  '/prontuarios': typeof AppProntuariosIndexRoute
  '/relatorios': typeof AppRelatoriosIndexRoute
  '/servicos': typeof AppServicosIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/agenda/': typeof AppAgendaIndexRoute
  '/_app/ajuda/': typeof AppAjudaIndexRoute
  '/_app/assinatura/': typeof AppAssinaturaIndexRoute
  '/_app/auditoria/': typeof AppAuditoriaIndexRoute
  '/_app/caixa/': typeof AppCaixaIndexRoute
  '/_app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/_app/financeiro/': typeof AppFinanceiroIndexRoute
  '/_app/pacientes/': typeof AppPacientesIndexRoute
  '/_app/profissionais/': typeof AppProfissionaisIndexRoute
  '/_app/prontuarios/': typeof AppProntuariosIndexRoute
  '/_app/relatorios/': typeof AppRelatoriosIndexRoute
  '/_app/servicos/': typeof AppServicosIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/agenda'
    | '/ajuda'
    | '/assinatura'
    | '/auditoria'
    | '/caixa'
    | '/configuracoes'
    | '/financeiro'
    | '/pacientes'
    | '/profissionais'
    | '/prontuarios'
    | '/relatorios'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/agenda'
    | '/ajuda'
    | '/assinatura'
    | '/auditoria'
    | '/caixa'
    | '/configuracoes'
    | '/financeiro'
    | '/pacientes'
    | '/profissionais'
    | '/prontuarios'
    | '/relatorios'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/onboarding/'
    | '/_app/agenda/'
    | '/_app/ajuda/'
    | '/_app/assinatura/'
    | '/_app/auditoria/'
    | '/_app/caixa/'
    | '/_app/configuracoes/'
    | '/_app/financeiro/'
    | '/_app/pacientes/'
    | '/_app/profissionais/'
    | '/_app/prontuarios/'
    | '/_app/relatorios/'
    | '/_app/servicos/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/login",
        "/onboarding/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/dashboard",
        "/_app/agenda/",
        "/_app/ajuda/",
        "/_app/assinatura/",
        "/_app/auditoria/",
        "/_app/caixa/",
        "/_app/configuracoes/",
        "/_app/financeiro/",
        "/_app/pacientes/",
        "/_app/profissionais/",
        "/_app/prontuarios/",
        "/_app/relatorios/",
        "/_app/servicos/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_app/dashboard": {
      "filePath": "_app/dashboard.tsx",
      "parent": "/_app"
    },
    "/onboarding/": {
      "filePath": "onboarding/index.tsx"
    },
    "/_app/agenda/": {
      "filePath": "_app/agenda/index.tsx",
      "parent": "/_app"
    },
    "/_app/ajuda/": {
      "filePath": "_app/ajuda/index.tsx",
      "parent": "/_app"
    },
    "/_app/assinatura/": {
      "filePath": "_app/assinatura/index.tsx",
      "parent": "/_app"
    },
    "/_app/auditoria/": {
      "filePath": "_app/auditoria/index.tsx",
      "parent": "/_app"
    },
    "/_app/caixa/": {
      "filePath": "_app/caixa/index.tsx",
      "parent": "/_app"
    },
    "/_app/configuracoes/": {
      "filePath": "_app/configuracoes/index.tsx",
      "parent": "/_app"
    },
    "/_app/financeiro/": {
      "filePath": "_app/financeiro/index.tsx",
      "parent": "/_app"
    },
    "/_app/pacientes/": {
      "filePath": "_app/pacientes/index.tsx",
      "parent": "/_app"
    },
    "/_app/profissionais/": {
      "filePath": "_app/profissionais/index.tsx",
      "parent": "/_app"
    },
    "/_app/prontuarios/": {
      "filePath": "_app/prontuarios/index.tsx",
      "parent": "/_app"
    },
    "/_app/relatorios/": {
      "filePath": "_app/relatorios/index.tsx",
      "parent": "/_app"
    },
    "/_app/servicos/": {
      "filePath": "_app/servicos/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
